blog/urls.py
from django.conf.urls import url
from .views import PostDetail, PostList, PostCreate, PostUpdate, PostDelete, PostArchiveYear, PostArchiveMonth

app_name = 'blog'

urlpatterns = [
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/$', PostArchiveYear.as_view(), name='post_archive_year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostArchiveMonth.as_view(), name='post_archive_month'),
    url(r'^create/$', PostCreate.as_view(), name='post_create'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', PostDetail.as_view(), name='post_detail'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/update/$', PostUpdate.as_view(), name='post_update'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/delete/$', PostDelete.as_view(), name='post_delete'),
]

suorganizer/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.static import static

from contact import urls as contact_urls
from organizer.urls import startup as startup_urls
from organizer.urls import tag as tag_urls
from user import urls as user_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(
        pattern_name='blog:post_list'
    ), name='homepage'),
    url(r'^blog/', include('blog.urls')),
    url(r'^startup/', include(startup_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^about/$', TemplateView.as_view(
        template_name='site/about.html'), name='about'),
    url(r'^user/', include(user_urls)),
    url(r'^ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from organizer.models import Tag, Startup
from django.utils.text import slugify

from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

# each field provides
# 1. How the date is stored in the database
# 2. Which python data type will it be manupulated in
# 3. How to validate each field
# 4. How to diaplay data in certain context such as form

# Migration is version control of database (it put simply)

class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63, unique_for_month='pub_date', help_text='A label for URL config.')
    text = RichTextUploadingField(
        extra_plugins=['youtube',],
        external_plugin_resources=[
            (
                'youtube',
                '/static/ckeditor/ckeditor/plugins/youtube/',
                'plugin.js',
            )
        ]
    )
    pub_date = models.DateField('date published', auto_now_add=True) 
    tags = models.ManyToManyField(Tag, related_name='blog_posts', blank=True)
    startups = models.ManyToManyField(Startup, related_name='blog_posts', blank=True)

    class Meta:
        verbose_name = 'blog post'
        ordering = ['-pub_date', 'title']
        get_latest_by = 'pub_date'
        permissions = (
            ("view_future_post",
             "Can View unpublished Post"),
        )


    def __str__(self):
        return "{} on {}".format(self.title, self.pub_date.strftime('%d-%m-%Y'))

    def save(self, *args, **kwargs):
        if not self.slug:
           self.slug = slugify(self.title)

        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={
            'year':self.pub_date.year,
            'month':self.pub_date.month,
            'slug':self.slug
        })
    
    def get_update_url(self):
        return reverse('blog:post_update', kwargs={
            'year': self.pub_date.year,
            'month': self.pub_date.month,
            'slug': self.slug
        })

    def get_delete_url(self):
        return reverse('blog:post_delete', kwargs={
            'year': self.pub_date.year,
            'month': self.pub_date.month,
            'slug': self.slug
        })
    
    def get_archive_year_url(self):
        return reverse('blog:post_archive_year', kwargs={'year':self.pub_date.year})

    def get_archive_month_url(self):
        return reverse('blog:post_archive_month', kwargs={
            'year':self.pub_date.year,
            'month':self.pub_date.month
        })


        

blog/forms.py
from django import forms
from django.utils.text import slugify

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('slug',)
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control'
            }),
            'tag': forms.SelectMultiple(attrs={
                'class': 'form-control'
            }),
            'startup': forms.SelectMultiple(attrs={
                'class':'form-control'
            })
        }
    
    def clean(self):
        cleaned_data=super().clean()
        cleaned_data['slug']=slugify(cleaned_data.get('title'))
        return cleaned_data
        
    

blog/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy

# Create your views here.
from django.views.generic import (ListView, CreateView, UpdateView, DetailView,
                                    YearArchiveView, ArchiveIndexView, MonthArchiveView,
                                    DateDetailView, DeleteView)
from django.views.decorators.http import require_http_methods
from django.shortcuts import render, get_object_or_404


from .models import Post
from .forms import PostForm
from organizer.utils import PageLinkMixin
from .utils import DateObjectMixin, AllowFuturePermissionMixin
from user.decorators import required_authenticated_permissions

# def post_list(request):
#     return render(request, 'blog/post_list.html', {'post_list':Post.objects.all()})

class PostList(AllowFuturePermissionMixin ,PageLinkMixin ,ArchiveIndexView):
    model = Post
    allow_empty = True
    context_object_name = 'post_list'
    date_field = 'pub_date'
    paginate_by = 5
    template_name_suffix = '_list'
    make_object_list = True


class PostArchiveYear(AllowFuturePermissionMixin ,YearArchiveView):
    model = Post
    date_field = 'pub_date'
    make_object_list = True


class PostArchiveMonth(AllowFuturePermissionMixin ,MonthArchiveView):
    model = Post
    date_field = 'pub_date'
    month_format = "%m"

# @require_http_methods(['GET', 'HEAD'])
# def post_detail(request, year, month, slug):
#     post = get_object_or_404(Post, pub_date__year=year, pub_date__month=month, slug=slug)
#     return render(
#         request,
#         'blog/post_detail.html',
#         {'post':post}
#     )


class PostDetail(DateObjectMixin ,DetailView):
    model = Post


@required_authenticated_permissions('blog.add_post')
class PostCreate(CreateView):
    template_name = 'blog/post_form.html'
    form_class = PostForm

@required_authenticated_permissions('blog.change_post')
class PostUpdate(DateObjectMixin ,UpdateView):
    template_name = 'blog/post_update_form.html'
    form_class = PostForm
    model = Post
        
@required_authenticated_permissions('blog.delete_post')
class PostDelete(DateObjectMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

blog/templates/blog/base_blog.html
{% extends parent_template|default:'base.html' %}
{% load staticfiles %}
{% block css_block %}
<link rel="stylesheet" href="{% static 'blog/blog.css' %}">
{% endblock css_block %}

blog/templates/blog/post_archive_month.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - {{month|date:'N Y'}} Posts
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-8">
        <h2>All Post for {{month|date:"F Y"}}</h2>
        {% for post in post_list %}
        <article>
            <header>
                <h2>
                    <a href="{{post.get_absolute_url}}">{{post.title|title}}</a>
                </h2>
                <p>
                    Written on:
                    <time datetime="{{post.pub_date|date:'Y-m-d'}}">
                        {{post.pub_date|date:"l, F j, Y"}}
                    </time>
                </p>
                 {% if perms.blog.change_post or perms.delete_post %}
                <table>
                    <tr>
                        {% if perms.blog.change_post %}
                        <th>
                            <button class="btn btn-sm btn-outline-primary">
                                <a href="{{post.get_update_url}}">Edit Post</a>
                            </button>
                        </th>
                        {% endif %} {% if perms.blog.delete_post %}
                        <th>
                            <button class="btn btn-sm btn-outline-danger">
                                <a href="{{post.get_delete_url}}">Delete</a>
                            </button>
                        </th>
                        {% endif %}
                    </tr>
                </table>
                {% endif %}
        
            </header>
        
            <p>{{post.text|truncatewords:20}}</p>
            <p>
                <a href="{{post.get_absolute_url}}">Read more&hellip;</a>
            </p>
        </article>
        {% endfor %}
    </div>
    <div class="col-sm-4">
        <div class="sidebar">
            {% if perms.blog.add_post %}
            <div class="sidechild btn btn-link">
                <a href="{% url 'blog:post_create' %}">
                    Write New Post
                </a>
            </div>
            {% endif %}
            <div class="sidechild btn btn-link">
                <a href="{% url 'blog:post_archive_year' month|date:"Y" %}">
                    All posts from {{month|date:"Y"}}
                </a>
            </div>
            <div class="sidechild btn btn-link">
                <a href="{% url 'blog:post_list' %}">
                    Latest Posts
                </a>
            </div>
        </div>
    </div>
</div>
<div></div>
{% endblock content %}

blog/templates/blog/post_archive_year.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - {{year|date:"Y"}} Posts         
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-8">
        <h2>All Post for {{year|date:'Y'}}</h2>
        {% for post in post_list %}
        <article>
            <header>
                <h2>
                    <a href="{{post.get_absolute_url}}">{{post.title|title}}</a>
                </h2>
                <p>
                    Written on:
                    <time datetime="{{post.pub_date|date:'Y-m-d'}}">
                        {{post.pub_date|date:"l, F j, Y"}}
                    </time>
                </p>
                 {% if perms.blog.change_post or perms.delete_post %}
                <table>
                    <tr>
                        {% if perms.blog.change_post %}
                        <th>
                            <button class="btn btn-sm btn-outline-primary">
                                <a href="{{post.get_update_url}}">Edit Post</a>
                            </button>
                        </th>
                        {% endif %} {% if perms.blog.delete_post %}
                        <th>
                            <button class="btn btn-sm btn-outline-danger">
                                <a href="{{post.get_delete_url}}">Delete</a>
                            </button>
                        </th>
                        {% endif %}
                    </tr>
                </table>
                {% endif %}
        
            </header>
        
            <p>{{post.text|truncatewords:20}}</p>
            <p>
                <a href="{{post.get_absolute_url}}">Read more&hellip;</a>
            </p>
        </article>
        {% endfor %}
    </div>
    <div class="col-sm-4">
        <h3>Archive By Month</h3>
        <ul>
            {% for m in date_list %}
            <li>
                <a href="{% url 'blog:post_archive_month' year=m|date:"Y" month=m|date:"n" %}">{{m|date:"F Y"}}</a>
            </li>
            {% endfor %}
        </ul>
        <a href="{% url 'blog:post_list' %}">Latest Post</a>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <div class="row">
            <div class="col-sm-6">
                {% if previous_year %}
                <a href="{% url 'blog:post_archive_year' year=previous_year|date:'Y' %}">Previous Year</a>
                {% endif %}
            </div>
            <div class="col-sm-6 text-right">
                {% if next_year %}
                <a href="{% url 'blog:post_archive_year' year=next_year|date:'Y' %}">Next Year</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends parent_template|default:'blog/base_blog.html' %} 
{% block title %} {{ block.super }} - Delete Post 
{% endblock title %} 
{% block content %}
<div class="container">
    <div>
        <form action="{{post.get_delete_url}}" method="post">
            {% csrf_token %} 
            <p>Are you sure you want to delete post {{post.title}}?</p>
            <table>
                <tr>
                    <th>
                        <button class="btn btn-outline-primary">
                            <a href="{{post.get_absolute_url}}">Cancle</a>
                        </button>
                    </th>
                    <th>
                        <button type="submit" class="btn btn-outline-danger">Delete Post</button>
                    </th>
                </tr>
            </table>
        </form>
    </div>
</div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends parent_template|default:'blog/base_blog.html' %}
{% block title %}
{{ block.super }} - {{post.title|title}}
{% endblock title %}
{% block content %}
<article>
    <header>
        <h2>{{post.title|title}}</h2>
        <p>
            Written on
            <time datetime="{{post.pub_date|date:"d-m-Y"}}">
                {{post.pub_date|date:"l, F j, Y"}}
            </time>
        </p>
        {% if perms.blog.change_post or perms.delete_post  %}
        <table>
            <tr>
                {% if perms.blog.change_post %}
                <th>
                    <button class="btn btn-sm btn-outline-primary">
                        <a href="{{post.get_update_url}}">Edit Post</a>
                    </button>
                </th>
                {% endif %}
                {% if perms.blog.delete_post %}
                <th>
                    <button class="btn btn-sm btn-outline-danger">
                        <a href="{{post.get_delete_url}}">Delete</a>
                    </button>
                </th>
                {% endif %}
            </tr>
        </table>
        {% endif %}
    </header>
    {{post.text|safe}} 
    {% if post.startups.all or post.tags.all %}
    <footer>
        {% if post.startups.all %}
        <section>
            <h3>Startup{{post.startups.count|pluralize}}</h3>
            <ul>
                {% for startup in post.startups.all %}
                <li>
                    <a href="{{startup.get_absolute_url }}">{{startup.name}}</a>
                </li>
                {% endfor %}
            </ul>
        </section>
        {% endif %} {% if post.tags.all %}
        <section>
            <h3>Tag{{post.tags.count|pluralize}}</h3>
            <ul>
                {% for tag in post.tags.all %}
                <li>
                    <a href="{{tag.get_absolute_url}}">{{tag.name|title}}</a>
                </li>
                {% endfor %}
            </ul>
        </section>
        {% endif %}
    </footer>
    {% endif %}
</article>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends parent_template|default:'blog/base_blog.html' %}

{% block title %}
{{ block.super }} - Create Post
{% endblock title %}

{% block content %}
<div class="container">
    <div>
        <form action="{% url 'blog:post_create' %}" method="post">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Create Post</button>
        </form>
    </div>
</div>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends parent_template|default:'blog/base_blog.html' %}
{% block title %}
{{ block.super }} - Post List
{% endblock title %}
{% block content %}
<h1>Latest Posts</h1>
<div class="row">
    <div class="col-sm-8">
        {% if perms.blog.add_post %}
        <div class="write-post">
            <a href="{% url 'blog:post_create' %}">Write a new Post</a>
        </div>
        {% endif %}
        {% for post in post_list %}
        <article>
            <header>
                <h2>
                    <a href="{{post.get_absolute_url}}">{{post.title|title}}</a>
                </h2>
                <p>
                    Written on:
                    <time datetime="{{post.pub_date|date:'Y-m-d'}}">
                        {{post.pub_date|date:"l, F j, Y"}}
                    </time>
                </p>
                {% if perms.blog.change_post or perms.blog.delete_post %}
                <table>
                    <tr>
                        {% if perms.blog.change_post %}
                        <th>
                            <button class="btn btn-sm btn-outline-primary">
                                <a href="{{post.get_update_url}}">Edit Post</a>
                            </button>
                        </th>
                        {% endif %}
                        {% if perms.blog.delete_post %}
                        <th>
                            <button class="btn btn-sm btn-outline-danger">
                                <a href="{{post.get_delete_url}}">Delete</a>
                            </button>
                        </th>
                        {% endif %}
                    </tr>
                </table>
                {% endif %}
            </header>
        
            <p>{{post.text|truncatewords:20|safe}}</p>
            <p>
                <a href="{{post.get_absolute_url}}">Read more&hellip;</a>
            </p>
        </article>
        {% empty %}
        <p>
            <em>No Blog Posts Available</em>
        </p>
        {% endfor %}
    </div>
    <div class="col-sm-4">
        <h3>Year Archive</h3>
        <ul>
            {% for y in date_list %}
            <li>
                <a href="{% url 'blog:post_archive_year' y|date:"Y" %}">{{y|date:"Y"}}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if previous_page_url %}
        <li class="page-item">
            <a class="page-link" href="{{previous_page_url}}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %} {% for page_number in paginator.page_range %} {% if page_obj.number is page_number %}
        <li class="page-item active">
            <a class="page-link" href="?{{page_kwarg}}={{page_number}}">{{page_number}}
                <span class="sr-only">(current)</span>
            </a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?{{page_kwarg}}={{page_number}}">{{page_number}}</a>
        </li>
        {% endif %} {% endfor %} {% if next_page_url %}
        <li class="page-item">
            <a class="page-link" href="{{next_page_url}}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock content %}

blog/templates/blog/post_update_form.html
{% extends parent_template|default:'blog/base_blog.html' %} 

{% block title %} 
{{ block.super }} - Update Post
{% endblock title %} 

{% block content %}
<div class="container">
    <div>
        <form action="{{post.get_update_url}}" method="post">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Update Post</button>
        </form>
    </div>
</div>
{% endblock content %}