blog/urls.py
from django.conf.urls import url
from .views import PostDetail, PostList, PostCreate, PostUpdate, PostDelete, PostArchiveYear, PostArchiveMonth

app_name = 'blog'

urlpatterns = [
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/$', PostArchiveYear.as_view(), name='post_archive_year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostArchiveMonth.as_view(), name='post_archive_month'),
    url(r'^create/$', PostCreate.as_view(), name='post_create'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', PostDetail.as_view(), name='post_detail'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/update/$', PostUpdate.as_view(), name='post_update'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/delete/$', PostDelete.as_view(), name='post_delete'),
]

suorganizer/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.static import static

from contact import urls as contact_urls
from organizer.urls import startup as startup_urls
from organizer.urls import tag as tag_urls
from user import urls as user_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(
        pattern_name='blog:post_list'
    ), name='homepage'),
    url(r'^blog/', include('blog.urls')),
    url(r'^startup/', include(startup_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^about/$', TemplateView.as_view(
        template_name='site/about.html'), name='about'),
    url(r'^user/', include(user_urls)),
    url(r'^ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/models.py
from datetime import date

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=31)
    slug = models.SlugField()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_tag:detail', kwargs={'slug':self.slug})

    def get_update_url(self):
        return reverse('organizer_tag:update', kwargs={'slug': self.slug})
    
    def get_delete_url(self):
        return reverse('organizer_tag:delete', kwargs={'slug': self.slug})
    
    def published_posts(self):
        return self.blog_posts.filter(
            pub_date__lt=date.today()
        )


class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField(max_length=31, unique=True, help_text="A label for url config.")
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag, related_name='startups', blank=True)

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_startup:detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('organizer_startup:update', kwargs={'slug': self.slug})
    
    def get_delete_url(self):
        return reverse('organizer_startup:delete', kwargs={'slug':self.slug})
    
    def get_newslink_create_url(self):
        return reverse('organizer_startup:newslink_create', kwargs={
            'startup_slug': self.slug
        })
    
    def published_posts(self):
        return self.blog_posts.filter(
            pub_date__lt=date.today()
        )


class Newslink(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup)

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'
        unique_together = ('slug','startup')

    def __str__(self):
        return "{}:{}".format(self.startup, self.title)
    
    def get_absolute_url(self):
        return self.startup.get_absolute_url()

    def get_update_url(self):
        return reverse('organizer_startup:newslink_update', kwargs={
            'newslink_slug': self.slug,
            'startup_slug': self.startup.slug
        })
    
    def get_delete_url(self):
        return reverse('organizer_startup:newslink_delete', kwargs={
            'newslink_slug': self.slug,
            'startup_slug': self.startup.slug
        })
    
    

organizer/forms.py
from django import forms

from .models import Tag, Startup, Newslink
from .utils import SlugCleanMixin


class TagForm(SlugCleanMixin ,forms.ModelForm):

    class Meta:
        model = Tag
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Enter desired tag name'
            }),
            'slug': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter slug'
            })
        }

    def clean_name(self):
        name = self.cleaned_data['name']
        return name.lower()

    
class StartupForm(SlugCleanMixin ,forms.ModelForm):
    
    class Meta:
        YEARS = ['2000', '2001', '2002', '2003', '2004',
                 '2005', '2006', '2007', '2008', '2009', '2010','2011','2012','2013','2014','2015','2016','2017','2018']
        model = Startup
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'slug': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control'
            }),
            'founded_date': forms.SelectDateWidget(years=YEARS),
            'contact': forms.EmailInput(attrs={
                'class': 'form-control'
            }),
            'website': forms.URLInput(attrs={
                'class': 'form-control',
            })
        }


    
class NewslinkForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Newslink
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'slug': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'pub_date':forms.SelectDateWidget,
            'link': forms.URLInput(attrs={
                'class': 'form-control'
            }),
            'startup': forms.HiddenInput()
        }
        
    
    def clean_slug(self):
        return self.cleaned_data['slug'].lower()
    
    

organizer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (View, ListView, DetailView,
                                  DeleteView, CreateView)
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator

from .models import Tag, Startup, Newslink
from .forms import TagForm, NewslinkForm, StartupForm
from .utils import (PageLinkMixin, StartupContextMixin, NewslinkGetObjectMixin)
from core.utils import UpdateView
from user.decorators import required_authenticated_permissions


#views relate to Tag.
class TagList(PageLinkMixin, ListView):
    model = Tag
    paginate_by = 5


class TagDetail(DetailView):
    model = Tag


@required_authenticated_permissions('organizer.add_tag')
class TagCreate(CreateView):
    form_class = TagForm
    template_name = 'organizer/tag_form.html'


@required_authenticated_permissions('organizer.change_tag')
class TagUpdate(UpdateView):
    model = Tag
    form_class = TagForm

@required_authenticated_permissions('organizer.delete_tag')
class TagDelete(DeleteView):
    model = Tag
    success_url = reverse_lazy('organizer:tag_list')


#views relate to startup
class StartupList(PageLinkMixin, ListView):
    model = Startup
    paginate_by = 5


class StartupDetail(DetailView):
    model = Startup

@required_authenticated_permissions('organizer.add_startup')
class StartupCreate(CreateView):
    form_class = StartupForm
    template_name = 'organizer/startup_form.html'

@required_authenticated_permissions('organizer.change_update')
class StartupUpdate(UpdateView):
    form_class = StartupForm
    model = Startup

@required_authenticated_permissions('oranizer.delete_startup')
class StartupDelete(DeleteView):
    model = Startup
    success_url = reverse_lazy('organizer:startup_list')

#views relate to Newslink


@required_authenticated_permissions('oranizer.create_newslink')
class NewslinkCreate(NewslinkGetObjectMixin, StartupContextMixin, CreateView):
    form_class = NewslinkForm
    template_name = 'organizer/newslink_form.html'
    model = Newslink

    def get_initial(self):
        startup_slug = self.kwargs.get(
            self.startup_slug_url_kwarg
        )
        self.startup = get_object_or_404(
            Startup,
            slug__iexact=startup_slug
        )
        initial = {
            self.startup_context_object_name: self.startup
        }
        initial.update(self.initial)
        return initial

@required_authenticated_permissions('organizer.change_newslink')
class NewslinkUpdate(NewslinkGetObjectMixin, StartupContextMixin, UpdateView):
    form_class = NewslinkForm
    model = Newslink
    slug_url_kwarg = 'newslink_slug'

@required_authenticated_permissions('organizer.delete_newslink')
class NewslinkDelete(NewslinkGetObjectMixin ,StartupContextMixin, DeleteView):
    model = Newslink
    slug_url_kwarg = 'newslink_slug'
  

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}
{% load staticfiles %}
{% block css_block %}
<link rel="stylesheet" href="{% static 'organizer/organizer.css' %}">
{% endblock css_block %}

{% block content %}
    {% block org_content %} 

    {% endblock org_content %} 

    <!-- bootstrap-pagination -->
    {% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if previous_page_url %}
            <li class="page-item">
                <a class="page-link" href="{{previous_page_url}}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            {% endif %}

            {% for page_number in paginator.page_range %}
            {% if page_obj.number is page_number %}
            <li class="page-item active">
                <a class="page-link" href="?{{page_kwarg}}={{page_number}}">{{page_number}}<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?{{page_kwarg}}={{page_number}}">{{page_number}}</a>
            </li>
            {% endif %}
            {% endfor %}
            
            {% if next_page_url %}
            <li class="page-item">
                <a class="page-link" href="{{next_page_url}}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
{% endblock content %}

organizer/templates/organizer/newslink_confirm_delete.html
{% extends parent_template|default:'organizer/base_organizer.html' %}

{% block title %}
{{ block.super }} - Delete News Article
{% endblock title %}

{% block content %}
<div class="container">
    <div>
        <form action="{{newslink.get_delete_url}}" method="post">
            {% csrf_token %}
            Are you sure you want to delete News Article {{newslink.title}}?
            <button class="btn btn-primary"><a href="{{newslink.get_absolute_url}}">Cancle</a></button>
            <button type="submit" class="btn btn-danger">Delink News</button>
        </form>
    </div>
</div>
{% endblock content %}

organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:'organizer/base_organizer.html' %}

{% block title %}
{{ block.super }} - Link News Article to Startup
{% endblock title %}

{% block content %}
{{startup.name}}

<div class="container">
    <div>
        <form action="{{startup.get_newslink_create_url}}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Link News</button>
        </form>
    </div>
</div>
{% endblock content %}

organizer/templates/organizer/newslink_form_update.html
{% extends parent_template|default:'organizer/base_organizer.html' %}
{% block title %}
{{ block.super }} - Update News Article
{% endblock title %}

{% block content %}
<div class="container">
    <div>
        <form action="{{newslink.get_update_url}}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Update News</button>
        </form>
    </div>
</div>
{% endblock content %}

organizer/templates/organizer/startup_confirm_delete.html
{% extends parent_template|default:'organizer/base_organizer.html' %}
{% block title %}
{{ block.super }} - Delete Startup
{% endblock title %}

{% block content %}
<div class="container">
    <div>
        <form action="{{startup.get_delete_url}}" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete startup {{startup.name}}?</p>
            <button class="btn btn-outline-primary"><a href="{{startup.get_absolute_url}}">Cancle</a></button>
            <button type="submit" class="btn btn-outline-danger">Delete Startup</button>
        </form>
    </div>
</div>
{% endblock content %}

organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:'organizer/base_organizer.html' %}
{% block title %}
{{block.super}} - {{startup.name}}
{% endblock title %}
{% block content %}
<article>
    <h2>{{startup.name}}</h2>
     {% if perms.organizer.change_startup or perms.organizer.delete_startup %}
    <table>
        <tr>
            {% if perms.organizer.change_startup %}
            <th>
                <button class="btn btn-sm btn-outline-primary">
                    <a href="{{startup.get_update_url}}">Update Startup</a>
                </button>
            </th>
            {% endif %} {% if perms.organizer.delete_startup %}
            <th>
                <button class="btn btn-sm btn-outline-danger">
                    <a href="{{startup.get_delete_url}}">Delete</a>
                </button>
            </th>
            {% endif %}
        </tr>
    </table>
    {% endif %}
    <dl>
        <dt>Date Founded</dt>
        <dd>{{startup.founded_date|date:"jS F Y"}}</dd>
        <dt>Website</dt>
        <dd>{{startup.website}}</dd>
        <dt>Contact</dt>
        <dd>{{startup.contact}}</dd>
        <dt>Tag{{startup.tags.count|pluralize}}</dt>
        {% for tag in startup.tags.all %}
        <dd>
            <a href="{{tag.get_absolute_url}}">{{tag.name|title}}</a>
        </dd>
        {% empty %} {% endfor %}
    </dl>

    <p>
        {{startup.description|linebreaks}}
    </p>
    <p>
        <a href="{{startup.get_newslink_create_url}}">Add Article</a>
    </p>
    {% if startup.newslink_set.all %}
    <section>
        <h3>Recent News</h3>
        <ul>
            {% for newslink in startup.newslink_set.all %}
            <li>
                <a href="{{newslink.link}}">{{newslink.title}}</a>
                {% if perms.organizer.change_newslink or perms.organizer.delete_tag %}
                <table>
                    <tr>
                        {% if perms.organizer.change_newslink %}
                        <th>
                            <button class="btn btn-sm btn-outline-primary">
                                <a href="{{newslink.get_update_url}}">Update Newslink</a>
                            </button>
                        </th>
                        {% endif %}
                        {% if perms.organizer.delete_newslink %}
                        <th>
                            <button class="btn btn-sm btn-outline-danger">
                                <a href="{{newslink.get_delete_url}}">Delete</a>
                            </button>
                        </th>
                        {% else %}
                        {% endif %}
                    </tr>
                </table>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </section>
    {% endif %} 
     {% if perms.blog.view_future_post %} {% if startup.blog_posts.all %}
    <section>
        <h3>Blog Post{{startup.blog_posts.count|pluralize}}</h3>
        <ul>
            {% for post in startup.blog_posts.all %}
            <li>
                <a href="{{post.get_absolute_url}}">{{post.title|title}}</a>
            </li>
            {% endfor %}
        </ul>
    </section>
    {% endif %} {% else %}
    <section>
        <h3>Blog Post{{startup.published_posts|pluralize}}</h3>
        <ul>
            {% for post in startup.published_posts %}
            <li>
                <a href="{{post.get_absolute_url}}">{{post.title|title}}</a>
            </li>
            {% endfor %}
        </ul>
    </section>
    {% endif %}
</article>
{% endblock content %}

organizer/templates/organizer/startup_form.html
{% extends parent_template|default:'organizer/base_organizer.html' %}

{% block title %}
{{ block.super }} - Create Startup
{% endblock title %}

{% block content %}
<div class="container">
    <div>
        <form action="{% url 'organizer_startup:create' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Create Startup</button>
        </form>
    </div>
</div>
{% endblock content %}

organizer/templates/organizer/startup_form_update.html
{% extends parent_template|default:'organizer/base_organizer.html' %}

{% block title %}
{{ block.super }} - Update Startup
{% endblock title %}

{% block content %}
<div class="container">
    <div>
        <form action="{{startup.get_update_url}}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Update Startup</button>
        </form>
    </div>
</div>
{% endblock content %}

organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
{{block.super}} - Startups
{% endblock title %}
{% block org_content %}
<h2>Startup List</h2>
{% if perms.organizer.add_startup %}
<div class="add-organizer">
    <a href="{% url 'organizer_startup:create' %}">Add a new Startup</a>
</div>
{% endif %}
<ul>
    {% for startup in startup_list %}
    <li>
        <a href="{{startup.get_absolute_url}}">{{startup.name}}</a>
    </li>
    {% if perms.organizer.change_startup or perms.organizer.delete_startup %}
    <table>
        <tr>
            {% if perms.organizer.change_startup %}
            <th>
                <button class="btn btn-sm btn-outline-primary">
                    <a href="{{startup.get_update_url}}">Update Startup</a>
                </button>
            </th>
            {% endif %}
            {% if perms.organizer.delete_startup %}
            <th>
                <button class="btn btn-sm btn-outline-danger">
                    <a href="{{startup.get_delete_url}}">Delete</a>
                </button>
            </th>
            {% endif %}
        </tr>
    </table>
    {% endif %}
    {% empty %}
    <li>
        <em>No Startups Available</em>
    </li>
    {% endfor %}
</ul>
{% endblock %}

organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Tag
{% endblock title %}

{% block content %}
<div class="container">
    <div>
        <form action="{{tag.get_delete_url}}" method="post">
            {% csrf_token %}
            <p>
                Are you sure you want to delete tag {{tag.name}}
            </p>
            <button class="btn btn-primary"><a href="{{tag.get_absolute_url}}">Cancel</a></button>
            <button type="submit" class="btn btn-danger">Delete Tag</button>
        </form>
    </div>
</div>
{% endblock content %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
{{block.super}} - {{tag.name|title}}
{% endblock title %}
{% block content %}
<h2>{{tag.name|title}}</h2>
{% if perms.organizer.change_tag or perms.organizer.delete_tag %}
<table>
    <tr>
        {% if perms.organizer.change_tag %}
        <th>
            <button class="btn btn-sm btn-outline-primary">
                <a href="{{tag.get_update_url}}">Edit Tag</a>
            </button>
        </th>
        {% endif %}
        {% if perms.organizer.delete_tag %}
        <th>
            <button class="btn btn-sm btn-outline-danger">
                <a href="{{tag.get_delete_url}}">Delete</a>
            </button>
        </th>
        {% endif %}
    </tr>
</table>
{% endif %}
{% if tag.startups.all %}
<section>
    <h3>Startup{{tag.startups.count|pluralize}}</h3>
    <p>This tag is associated with {{tag.startups.count}} startup{{tag.startups.count|pluralize}}</p>
    <ul>
        {% for startup in tag.startups.all %}
        <li>
            <a href="{{startup.get_absolute_url}}">{{startup.name}}</a>
        </li>
        {% endfor %}
    </ul>
</section>
{% endif %} 
{% if perms.blog.view_future_post %}
    {% if tag.blog_posts.all %}
    <section>
        <h3>Blog Post{{tag.blog_posts.count|pluralize}}</h3>
        <ul>
            {% for post in tag.blog_posts.all %}
            <li>
                <a href="{{post.get_absolute_url}}">{{post.title|title}}</a>
            </li>
            {% endfor %}
        </ul>
    </section>
    {% endif %}
{% else %}
    <section>
        <h3>Blog Post{{tag.published_posts|pluralize}}</h3>
        <ul>
            {% for post in tag.published_posts %}
            <li>
                <a href="{{post.get_absolute_url}}">{{post.title|title}}</a>
            </li>
            {% endfor %}
        </ul>
    </section>
{% endif %} 
{% if not tag.startups.all and not tag.blog_posts.all %}
<p>This tag is not releted to any content.</p>
{% endif %}
{% endblock content %}

organizer/templates/organizer/tag_form.html
{% extends parent_template|default:'organizer/base_organizer.html' %}
{% block title %}
{{ block.super }} - Create Tag
{% endblock title %}

{% block content %}
 <div class="container">
     <div>
        <form action="{% url 'organizer_tag:create' %}" method="post">
            {% csrf_token %} 
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Create Tag</button>
        </form>
     </div>
 </div>
{% endblock content %}

organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:'organizer/base_organizer.html' %}
{% block title %}
{{ block.super }} - Update Tag
{% endblock title %}

{% block content %}
<div class="container">
    <div>
        <form action="{{tag.get_update_url}}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Update Tag</button>
        </form>
    </div>
</div>
{% endblock content %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
{{block.super}} - Tag List
{% endblock title %}
{% block org_content %}
<h2>Tag List</h2>
    {% if perms.organizer.add_tag %}
    <div class="add-organizer active">
        <a href="{% url 'organizer_tag:create' %}">Create New Tag</a>
    </div>
    {% endif %}
<ul>
    {% for tag in tag_list %}
    <li>
        <a href="{{tag.get_absolute_url}}">{{tag.name|title}}</a>
    </li>
    {% empty %}
    <p>
        <em>There are currently no tags available.</em>
    </p>
    {% endfor %}
</ul>
{% endblock %}