blog/urls.py
from django.conf.urls import url
from .views import PostDetail, PostList, PostCreate, PostUpdate, PostDelete, PostArchiveYear, PostArchiveMonth

app_name = 'blog'

urlpatterns = [
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/$', PostArchiveYear.as_view(), name='post_archive_year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostArchiveMonth.as_view(), name='post_archive_month'),
    url(r'^create/$', PostCreate.as_view(), name='post_create'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', PostDetail.as_view(), name='post_detail'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/update/$', PostUpdate.as_view(), name='post_update'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/delete/$', PostDelete.as_view(), name='post_delete'),
]

contact/urls.py
from django.conf.urls import url
from .views import ContactView

app_name='contact'

urlpatterns = [
    url(r'^$', ContactView.as_view(), name='contact')
]

suorganizer/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.static import static

from contact import urls as contact_urls
from organizer.urls import startup as startup_urls
from organizer.urls import tag as tag_urls
from user import urls as user_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(
        pattern_name='blog:post_list'
    ), name='homepage'),
    url(r'^blog/', include('blog.urls')),
    url(r'^startup/', include(startup_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^about/$', TemplateView.as_view(
        template_name='site/about.html'), name='about'),
    url(r'^user/', include(user_urls)),
    url(r'^ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView, TemplateView
from django.core.urlresolvers import reverse_lazy

from .views import (DisableAccount, ActivateAccount, CreateAccount, 
                    ResendActivationEmail, ProfileDetail, ProfileUpdate, PublicProfileDetail)
app_name = 'user'

password_urls = [
    #password change
    url(r'^$/', RedirectView.as_view(
        pattern_name = 'user:pw_reset_start',
        permanent=False
    )),
    url(r'^change/$', auth_views.password_change,
        {'template_name': 'user/password_change_form.html',
         'post_change_redirect': reverse_lazy('user:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$', auth_views.password_change_done,
        {'template_name': 'user/password_change_done.html'},
        name='pw_change_done'),
    #passowrd reset
    url(r'^reset/$',
        auth_views.password_reset,
        {
            'template_name': 'user/password_reset_form.html',
            'email_template_name': 'user/password_reset_email.txt',
            'subject_template_name': 'user/password_reset_subject.txt',
            'post_reset_redirect': reverse_lazy('user:pw_reset_sent')
        },
        name='pw_reset_start'),
    url(r'^reset/sent/$', auth_views.password_reset_done,
        {'template_name': 'user/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/(?P<uidb64>[0-9a-zA-Z_\-]+)/(?P<token>[0-9a-zA-Z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {
            'template_name': 'user/password_reset_confirm.html',
            'post_reset_redirect': reverse_lazy('user:pw_reset_complete'),
        },
        name='pw_reset_confirm'),
    url(r'^reset/done/$',
        auth_views.password_reset_done,
        {
            'template_name': 'user/password_reset_complete.html',
            'extra_context': {'form': AuthenticationForm}
        },
        name='pw_reset_complete'),
]

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='user:login', permanent=False)),
    url(r'^login/$', auth_views.login,
        {'template_name': 'user/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,
        {'template_name': 'user/logout.html',
         'extra_context': {'form': AuthenticationForm}}, name='logout'),
    url(r'^password/', include(password_urls)),
    url(r'^disable/$', DisableAccount.as_view(), name='disable'),
    url(r'^create/$', CreateAccount.as_view(), name='create'),
    url(r'^create/done/$', TemplateView.as_view(
        template_name='user/user_create_done.html'),
        name='create_done'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(), name='activate'),
    url(r'^activate/resend/$', ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate/', RedirectView.as_view(
        pattern_name='user:resend_activation',
        permanent=False
    )),
    url(r'^profile/$', ProfileDetail.as_view(), name='profile'),
    url(r'^profile/edit/$', ProfileUpdate.as_view(), name='profile_update'),
    url(r'^(?P<slug>[\w\-]+)/$', PublicProfileDetail.as_view(), name='public_profile')
]

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
        crossorigin="anonymous"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
            crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
        crossorigin="anonymous">
    {% block css_block %}
    
    {% endblock css_block %}
    <title>
        {% block title %}
        Startup Organizer
        {% endblock title %}
    </title>
</head>

<!-- importing url for using in navbar -->
{% url 'organizer_startup:list' as startup_list_link %}
{% url 'organizer_tag:list' as tag_list_link %}
{% url 'contact:contact' as contact_link %}
{% url 'about' as about_link %}
{% url 'user:logout' as logout_link %}
{% url 'user:login' as login_link %}

<body>
    {% include "navbar.html" %}
    {% if messages %}
    <div class="container">
        <div>
            <ul>
                {% for message in messages %}
                    {% if messages.tags %}
                        <li class="{{message.tags}}">
                    {% else %}
                    <li>
                    {% endif %}{{message}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    
    {% else %}
    {% endif %}
    <div class="container" style="margin-top:10px;">
        <header>
        </header>
        <main>
            {% block content %}
             This is default content!
            {% endblock content %}
        </main>
    </div>

    <footer>
        <p>
            &copy; {% now "Y" %}
            <a href="#">
            Rahul Bhaskar</a>
        </p>
        <p>
            Created for
            <a href="https://Django-Unleashed.com/">
            Django-Unleashed</a>
        </p>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
    {% block js_block %}
    
    {% endblock js_block %}
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% ifequal request.path startup_list_link %}active{% endifequal %}">
                    <a class="nav-link" href="{{startup_list_link}}">Startup</a>
                    <span class="sr-only">(current)</span>
                </li>
                <li class="nav-item {% ifequal request.path tag_list_link %}active{% endifequal %}">
                    <a class="nav-link" href="{{tag_list_link}}">Tag</a>
                    <span class="sr-only">(current)</span>
                </li>
                <li class="nav-item {% ifequal request.path contact_link %}active{% endifequal %}">
                    <a class="nav-link" href="{{contact_link}}">Contact Us</a>
                    <span class="sr-only">(current)</span>
                </li>
                <li class="nav-item {% ifequal request.path about_link %}active{% endifequal %}">
                    <a class="nav-link" href="{{about_link}}">About</a>
                    <span class="sr-only">(current)</span>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto navbar-right">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    {% if user.is_superuser %}
                    <a href="{% url 'admin:index' %}" target="_blank" class="nav-link">
                        Welcome {{user.username}}
                    </a>
                    {% else %}
                    <a href="#" class="nav-link">
                        Welcome {% if user.get_short_name %} {{user.get_short_name}} {% elif user.get_full_name %} {{user.get_full_name}} {% else%}
                        {{user.username}} {% endif %}
                    </a>
                    {% endif %}
                </li>
                <li class="nav-item {% ifequal request.path logout_link %}active{% endifequal %}">
                    <a href="{% url 'user:logout' %}?next={{request.path}}" class="nav-link">Logout</a>
                </li>
                <li class="nav-item"> 
                    <a href="{% url 'user:profile' %}" class="nav-link">View Profile</a>
                </li>
                {% else %}
                <li class="nav-item {% ifequal request.path login_link %}active{% endifequal %}">
                    <a href="{% url 'user:login' %}?next={{request.path}}" class="nav-link">Login</a>
                </li>
                <li class="nav-item {% ifequal request.path login_link %}active{% endifequal %}">
                    <a class="nav-link" href="{% url 'user:create' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>